# Generated by Django 4.1 on 2022-08-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
    ]
